### ISSUE TITLE
Directions for Wordpress 

### ISSUE THREAD

**Issue by dgmdevelopment** [anibalsanchez/lando-boilerplates-for-joomla-wordpress-and-prestashop#1]
Hi, I'm interested in the WP part of this.  I'm new to Lando, and I have been able to get the containers up with lando start, but I'm trying to automate the post install items like installing wordpress core and plugins.  Not sure how to do this.  Thank you for any guidance.

**Comment by anibalsanchez** [comment]
Hi,

You can use WP CLI. In the sample recipe, there is one command to install WordPress and Gutenberg plugin: https://github.com/anibalsanchez/lando-boilerplates-for-joomla-wordpress-and-prestashop/blob/master/wordpress/.lando.yml#L72

**Comment by anibalsanchez** [comment]
I've just documented the WP Recipe: https://github.com/anibalsanchez/lando-boilerplates-for-joomla-wordpress-and-prestashop#step-1---review-and-customize-the-recipe-for-wordpress

**Comment by dgmdevelopment** [comment]
Thank you for updating the recipe for WP!
